sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: w1277321189
  redis:
    host: localhost
    port: 6379
    password:
    database:
